/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PreparerLivraison.java
 *
 * Created on 2011-04-09, 13:50:49
 */

package inf5180_jdbc;

import inf5180_jdbc.table.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;

/**
 *
 * @author woworolandgamy
 */
public class PreparerLivraison extends javax.swing.JFrame implements ActionListener  {

    private static  String select1 = "" ;
    private static  String select2 = "" ;
    /** Creates new form PreparerLivraison */
    public PreparerLivraison(String nomFenetre) {
        initComponents();
        this.setTitle(nomFenetre);
        ajouterEvent () ;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Que voulez -vous faire ?"));

        jRadioButton1.setText("CONSULTER LES LIVRAISONS");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        jRadioButton2.setText("PROCEDER A UNE LIVRAISON");

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jRadioButton1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jRadioButton2)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jRadioButton1)
                    .add(jRadioButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1.setText("EXECUTER");

        jButton2.setText("FERMER");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                        .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 148, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(61, 61, 61)
                        .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 142, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(94, 94, 94))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(29, 29, 29)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jButton1)
                    .add(jButton2))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(28, 28, 28)
                .add(jPanel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration//GEN-END:variables


    private javax.swing.ButtonGroup groupeRadio  ;



    public void ajouterEvent () {

        groupeRadio = new javax.swing.ButtonGroup() ;
        groupeRadio.add (jRadioButton1) ;
        groupeRadio.add (jRadioButton2) ;

        jRadioButton1.setSelected (true) ;

        jButton1.addActionListener(this);
        jButton2.addActionListener(this);
        jRadioButton1.addActionListener(this);
        jRadioButton2.addActionListener (this) ;

    }
     public void fermerApplication (){
         addWindowListener (new WindowAdapter(){
          public void windowClosing (WindowEvent e) {
            System.exit (0) ;
           }
         }) ;
    }

     
    public void actionPerformed(ActionEvent e) {

        Object source = e.getSource() ;

         if (source == jButton1){
            if (jRadioButton1.isSelected () ){
                  ConsulterLivraison cosultation = new ConsulterLivraison ("Consulter Livraison") ;
                  cosultation.setVisible (true) ;
            }else {
                String value = JOptionPane.showInputDialog(null , "Entrez le numero du client: ", "Recherche du client", JOptionPane.QUESTION_MESSAGE) ;
                int valeur  ; 
                if (value == null || value.trim().length() == 0){
                    JOptionPane.showMessageDialog(this, "Valeur invalide", "ERREUR", JOptionPane.ERROR_MESSAGE);
                }else  {
                    // creation d'un enonce associ a la connexion
                     try{
                         valeur = Integer.parseInt(value) ;
                          select1 = "Select nom, prenom, plusGrandeQualite, telephone from Client where noClient = " + valeur ;
                          select2 = "Select numeroCivique, rue, ville, pays, codePostal " +
                                  "from Adresse where noClient =" + valeur + " and noFournisseur = 0" ;
                          JDBCDriverInformation.unEnonceSQL  = JDBCDriverInformation.con.createStatement() ;
                          ResultSet resultatSelect = JDBCDriverInformation.unEnonceSQL.executeQuery(select1) ;
                          int nb = 0 ;
                          Client c  = null ;
                          Adresse a = new Adresse () ;
                          if (resultatSelect.next()){
                              nb++ ;
                              c = new Client (valeur,resultatSelect.getString("nom"),
                                       resultatSelect.getString("prenom"),
                                       resultatSelect.getString("plusGrandeQualite"),
                                       resultatSelect.getString("telephone")) ;

                              resultatSelect = JDBCDriverInformation.unEnonceSQL.executeQuery(select2) ;
                              if (resultatSelect.next()){
                                a = new Adresse (resultatSelect.getString("numeroCivique"),
                                        resultatSelect.getString("rue"),
                                        resultatSelect.getString("ville"),
                                        resultatSelect.getString("pays"),
                                        resultatSelect.getString("codePostal")
                                        );

                              }
                          }
                          if (nb == 0)
                               JOptionPane.showMessageDialog(this, "CLIENT INEXISTANT", "ERREUR", JOptionPane.ERROR_MESSAGE);
                          else{
                            AffichageClient client = new AffichageClient ("Affichage du Client", c, a) ;
                            client.setVisible(true) ;
                          }
                     }catch (NumberFormatException i){
                        JOptionPane.showMessageDialog(this, i.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
                     }catch(SQLException f){
                         JOptionPane.showMessageDialog(this, f.getMessage(), "ERREUR", JOptionPane.ERROR_MESSAGE);
                     }

                 }
               
            }
         }else if (source == jButton2){
             fermerApplication () ;
             this.setVisible (false) ;
         }

    }
}
